# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='legislation',
            name='geo_coverage',
            field=models.CharField(choices=[('nat', 'National'), ('int-reg', 'International/regional'), ('st-pr', 'State/province'), ('city-mun', 'City/municipality'), ('oth', 'Other')], default=('nat', 'National'), max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='legislation',
            name='source',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='legislation',
            name='source_type',
            field=models.CharField(choices=[('official', 'Official'), ('unofficial', 'Unofficial')], default=('official', 'Official'), max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='legislation',
            name='website',
            field=models.URLField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='legislation',
            name='year_amendment',
            field=models.IntegerField(default=2017, null=True),
        ),
        migrations.AlterField(
            model_name='legislation',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ar', 'Arabic'), ('zh', 'Chinese'), ('fr', 'French'), ('ru', 'Russian'), ('es-es', 'Spanish'), ('oth', 'Other')], default=('en', 'English'), max_length=64),
        ),
        migrations.AlterField(
            model_name='legislation',
            name='law_type',
            field=models.CharField(choices=[('Constitution', 'Constitution'), ('Law', 'Law'), ('Regulation', 'Regulation'), ('oth', 'Other')], default=('Constitution', 'Constitution'), max_length=64),
        ),
    ]
