# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 15:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcc', '0002_auto_20171005_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='current_role',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='roles',
        ),
        migrations.DeleteModel(
            name='UserRole',
        ),
    ]
