# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 14:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lcc', '0003_auto_20171012_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment', to=settings.AUTH_USER_MODEL),
        ),
    ]
