# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcc', '0003_auto_20171017_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='affiliation',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Institutional affiliation'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='position',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Postition'),
        ),
    ]
