# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-20 10:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcc', '0004_auto_20171018_1411'),
        ('lcc', '0004_auto_20171019_0845'),
    ]

    operations = [
    ]
