# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-23 08:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcc', '0005_auto_20171023_0552'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together=set([('question', 'value', 'assessment')]),
        ),
    ]
