# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-26 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcc', '0006_auto_20171023_0822'),
        ('lcc', '0005_merge_20171020_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legislation',
            name='source_type',
            field=models.CharField(choices=[('official', 'Official'), ('unofficial', 'Unofficial'), ('', '----')], default=('official', 'Official'), max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='legislation',
            name='year_amendment',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='legislation',
            name='source',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='legislation',
            name='website',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='legislation',
            name='year_amendment',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='legislation',
            name='source_type',
            field=models.CharField(blank=True, choices=[('official', 'Official'), ('unofficial', 'Unofficial'), ('', '----')], default=('official', 'Official'), max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='legislation',
            name='classifications',
            field=models.ManyToManyField(blank=True, to='lcc.TaxonomyClassification'),
        ),
        migrations.AlterField(
            model_name='legislation',
            name='tags',
            field=models.ManyToManyField(blank=True, to='lcc.TaxonomyTag'),
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together=set([('question', 'assessment')]),
        ),
    ]
