# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-25 09:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcc', '0005_merge_20171020_1006'),
        ('lcc', '0006_auto_20171023_0822'),
    ]

    operations = [
    ]
