# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-25 15:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcc', '0007_auto_20171024_0921'),
        ('lcc', '0007_merge_20171025_1008'),
    ]

    operations = [
    ]
