# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-25 10:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lcc', '0007_merge_20171025_0949'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cw', models.BooleanField(default=False, verbose_name='CW')),
                ('small_cw', models.BooleanField(default=False, verbose_name='Small CW')),
                ('un', models.BooleanField(default=False, verbose_name='UN')),
                ('ldc', models.BooleanField(default=False, verbose_name='LDC')),
                ('lldc', models.BooleanField(default=False, verbose_name='LLDC')),
                ('sid', models.BooleanField(default=False, verbose_name='SID')),
                ('population', models.FloatField(null=True, verbose_name="Population ('000s) 2018")),
                ('hdi2015', models.FloatField(null=True, verbose_name='HDI2015')),
                ('gdp_capita', models.FloatField(null=True, verbose_name='GDP per capita, US$ 2016')),
                ('ghg_no_lucf', models.FloatField(null=True, verbose_name='Total GHG Emissions excluding LUCF MtCO2e 2014')),
                ('ghg_lucf', models.FloatField(null=True, verbose_name='Total GHG Emissions including LUCF MtCO2e 2014')),
                ('cvi2015', models.FloatField(null=True, verbose_name='Climate vulnerability index 2015')),
            ],
        ),
        migrations.CreateModel(
            name='FocusArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='LegalSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='PrioritySector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='SubRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
            ],
        ),
        migrations.AlterField(
            model_name='country',
            name='iso',
            field=models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='ISO'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='position',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Position'),
        ),
        migrations.AddField(
            model_name='countrymetadata',
            name='adaptation_priority_sectors',
            field=models.ManyToManyField(blank=True, to='lcc.PrioritySector'),
        ),
        migrations.AddField(
            model_name='countrymetadata',
            name='country',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='lcc.Country'),
        ),
        migrations.AddField(
            model_name='countrymetadata',
            name='legal_system',
            field=models.ManyToManyField(to='lcc.LegalSystem'),
        ),
        migrations.AddField(
            model_name='countrymetadata',
            name='mitigation_focus_areas',
            field=models.ManyToManyField(blank=True, to='lcc.FocusArea'),
        ),
        migrations.AddField(
            model_name='countrymetadata',
            name='region',
            field=models.ManyToManyField(to='lcc.Region'),
        ),
        migrations.AddField(
            model_name='countrymetadata',
            name='sub_region',
            field=models.ManyToManyField(to='lcc.SubRegion'),
        ),
        migrations.AddField(
            model_name='countrymetadata',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lcc.UserProfile'),
        ),
    ]
