# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-14 12:30
from __future__ import unicode_literals

from django.db import connection, migrations


def reset_ids(apps, schema_editor):
    """
    This makes sure the id's of the CountryMetadata objects in the database
    start from 1. This might not the case because a previous version of the
    CountryMetadata fixture loaded objects with ids starting from 200.
    """

    # We can't import the CountryMetadata model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    CountryMetadata = apps.get_model('lcc', 'CountryMetadata')
    data = None
    for data in CountryMetadata.objects.all():
        if data.id < 200:
            break
        data.id = data.id - 199
        data.save()

    if data:
        with connection.cursor() as cursor:
            cursor.execute(
                "ALTER SEQUENCE lcc_countrymetadata_id_seq RESTART WITH %s;",
                [data.id + 1]  # Next id should be the last one + 1
            )


class Migration(migrations.Migration):

    dependencies = [
        ('lcc', '0007_auto_20171106_1347'),
    ]

    operations = [
        migrations.RunPython(reset_ids),
    ]
