# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-19 16:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lcc', '0008_add_separate_assessment_profile_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='legislationarticle',
            name='identifier',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='assessmentprofile',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_profiles', to='lcc.Country'),
        ),
        migrations.AlterField(
            model_name='legislationpage',
            name='legislation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='lcc.Legislation'),
        ),
        migrations.AlterField(
            model_name='legislationarticle',
            name='code',
            field=models.CharField(max_length=256),
        )
    ]
