# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-26 14:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcc', '0009_auto_20171025_1546'),
        ('lcc', '0007_merge_20171025_1008'),
    ]

    operations = [
    ]
