# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-21 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcc', '0009_auto_20171215_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legislation',
            name='year',
            field=models.IntegerField(default=2018),
        ),
        migrations.AlterField(
            model_name='legislationpage',
            name='page_text',
            field=models.TextField(max_length=65535),
        ),
    ]
