# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-21 14:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lcc", "0010_auto_20180321_1356"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="taxonomytaggroup",
            options={"ordering": ["id"]},
        ),
    ]
