# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-23 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lcc", "0012_auto_20180417_0900"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="legislationarticle",
            options={"ordering": ["number", "code"]},
        ),
        migrations.AddField(
            model_name="legislationarticle",
            name="number",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
