# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-24 08:00

from __future__ import unicode_literals

import re

from django.db import migrations


def populate_article_numbers_from_code(apps, schema_editor):

    LegislationArticle = apps.get_model("lcc", "LegislationArticle")

    for article in LegislationArticle.objects.all():
        match = re.search("\d+", article.code)
        if match:
            article.number = int(match.group(0))
        article.save()


class Migration(migrations.Migration):

    dependencies = [
        ("lcc", "0013_auto_20180523_1338"),
    ]

    operations = [
        migrations.RunPython(
            populate_article_numbers_from_code, migrations.RunPython.noop
        ),
    ]
