# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-01-31 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcc', '0016_auto_20180615_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxonomyclassification',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
