# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-08-28 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lcc", "0020_userproxy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="legislation",
            name="year",
            field=models.IntegerField(default=2020),
        ),
    ]
