# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-10-14 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcc', '0021_auto_20200828_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='other_role',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Other role'),
        ),
        migrations.AlterField(
            model_name='legislation',
            name='year',
            field=models.IntegerField(default=2021),
        ),
    ]
