# Generated by Django 3.1.13 on 2021-09-14 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcc', '0022_auto_20210906_1225'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='legislationarticletree',
            options={'ordering': ['code']},
        ),
        migrations.RemoveIndex(
            model_name='legislationarticletree',
            name='lcc_legisla__classi_23f070_gin',
        ),
        migrations.RemoveIndex(
            model_name='legislationarticletree',
            name='lcc_legisla__tag_id_218d0f_gin',
        ),
        migrations.AlterField(
            model_name='legislationarticletree',
            name='code',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='legislationarticletree',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='legislationpage',
            name='page_text',
            field=models.TextField(),
        ),
    ]
