# Generated by Django 2.2.24 on 2021-09-15 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lcc', '0022_auto_20210906_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legislationarticle',
            name='legislation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_articles', to='lcc.Legislation'),
        ),
        migrations.AlterField(
            model_name='legislationarticletree',
            name='legislation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='lcc.Legislation'),
        ),
    ]
