# Generated by Django 3.1.13 on 2021-09-21 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcc', '0024_update_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='parent_answer',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
