# Generated by Django 3.1.13 on 2021-09-22 07:53

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcc', '0025_auto_20210921_1252'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='legislationsection',
            options={'ordering': ['number', 'code']},
        ),
        migrations.AddField(
            model_name='legislationsection',
            name='code_order',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddIndex(
            model_name='legislationsection',
            index=django.contrib.postgres.indexes.GinIndex(fields=['_classification_ids'], name='lcc_legisla__classi_793d08_gin'),
        ),
        migrations.AddIndex(
            model_name='legislationsection',
            index=django.contrib.postgres.indexes.GinIndex(fields=['_tag_ids'], name='lcc_legisla__tag_id_31b375_gin'),
        ),
    ]
