# Generated by Django 3.1.13 on 2022-05-18 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lcc', '0026_auto_20210922_0753'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogicalCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('code', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Logical category',
                'verbose_name_plural': 'Logical categories',
                'ordering': ['code'],
            },
        ),
        migrations.AlterModelOptions(
            name='legislationsection',
            options={'ordering': ['code_order']},
        ),
        migrations.AlterField(
            model_name='legislation',
            name='year',
            field=models.IntegerField(default=2022),
        ),
        migrations.AddField(
            model_name='taxonomyclassification',
            name='logical_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taxonomy_classifications', to='lcc.logicalcategory'),
        ),
    ]
